version: "3"

services:
  truffle:
    image: diginex/truffle
    build:
      context: .
    volumes:
      - ./truffle:/code/truffle
      - ./coverage:/code/coverage
      - ./scripts:/code/scripts
      - ./.babelrc:/code/.babelrc
      - ./.git:/code/.git

